---
- name: Display var host os family
  debug:
    var: ansible_os_family

- name: Display var host os distro
  debug:
    var: ansible_distribution

- name: Load OS specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution_major_version }}.yml"
        - "{{ ansible_os_family|lower }}-{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_distribution|lower }}.yml"
        - "{{ ansible_os_family|lower }}.yml"
        - defaults.yml
      paths:
        - ../vars

- name: Ensure required packages are installed (apt) Debian
  apt:
    name: "{{ item }}"
    update_cache: true
    state: installed
  with_items: "{{ packages|default([]) }}"
  when: ansible_os_family == "Debian" and ansible_distribution == "Debian"


- name: Debian - Install chkconfig
  apt:
    name: chkconfig
    state: present
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release == 'wheezy'

- name: Check if apt-transport-https is installed
  shell: dpkg-query -W 'apt-transport-https'
  ignore_errors: 'true'
  register: is_apthttps

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  when: is_apthttps | failed

- name: install ntp
  apt: pkg=ntp
  register: result
  until: result|succeeded
  retries: 5

- name: install ntp.conf
  template:
    dest: /etc/ntp.conf
    src: etc/ntp.conf
    mode: 0644
    owner: root
  notify:
    - restart-ntp

- name: ntp service enabled
  service:
    name: ntp
    state: started
    enabled: true

- name: Set nofile limits
  lineinfile: dest=/etc/security/limits.conf
              insertbefore="^# End of file"
              state=present
              line="{{ item }}"
  with_items:
    - "* soft nofile 63536"
    - "* hard nofile 32768"

- name: Set nproc limits
  lineinfile: dest=/etc/security/limits.d/90-nproc.conf
              insertafter=EOF
              state=present
              create=yes
              line="{{ item }}"
              mode=0644
  with_items:
    - "* soft nproc 32768"
    - "* hard nproc 32768"
