---
- name: install java
  apt: name=openjdk-7-jre

- name: install logstash
  apt: pkg=logstash
  notify: enable logstash

# this is pretty gross.   needs to be fixed better than this ... but for now it works.
# https://github.com/logstash-plugins/logstash-output-lumberjack/issues/11
- name: monkeypatch lumberjack ssl verify
  lineinfile:
    dest: /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.26/lib/lumberjack/client.rb
    regexp: "ssl_context.verify_mode"
    line: "        ssl_context.verify_mode = OpenSSL::SSL::VERIFY_NONE"
  notify: restart logstash

- name: logstash log directory
  file: dest=/var/log/logstash
        owner=logstash group=logstash mode=0750
        state=directory

- name: create cleversafe logs directory
  file: dest=/var/log/cleversafe_logs state=directory owner=logstash group=adm mode=0755

- name: remove logstash directory acl
  command: setfacl -b /var/log/logstash

- name: set up log rotation for logstash
  logrotate: name=logstash path=/var/log/logstash/*.log
  args:
    options:
      - "{{ logstash.logrotate.frequency }}"
      - "rotate {{ logstash.logrotate.rotations }}"
      - missingok
      - compress
      - copytruncate
      - delaycompress
      - notifempty

- name: set up log rotation for cleversafe logs
  logrotate: name=logstash path=/var/log/cleversafe_logs/*.log
  args:
    options:
      - "{{ logstash.logrotate.frequency }}"
      - "rotate {{ logstash.logrotate.rotations }}"
      - missingok
      - compress
      - copytruncate
      - delaycompress
      - notifempty

- name: configure logstash
  template: src={{ item }} dest=/{{ item }}
  with_items:
    - etc/default/logstash
  notify: restart logstash

- name: configure logstash pipeline
  template: src=etc/logstash/conf.d/pipeline.conf dest=/etc/logstash/conf.d/pipeline.conf
  notify: restart logstash

- name: install ssl cert package
  apt: pkg=ssl-cert

- name: create logstash ssl dir
  file:
    path: /etc/logstash/ssl
    state: directory
    owner: root
    group: logstash
    mode: 0750

- name: install ssl key
  template: src=etc/ssl/private/logstash.key
            dest=/etc/logstash/ssl/logstash.key
            owner=root group=logstash mode=0640
  notify: restart logstash

- name: install ssl cert
  template: src=etc/ssl/certs/logstash.pem
            dest=/etc/logstash/ssl/logstash.pem
            owner=root group=logstash mode=0640
  notify: restart logstash

- name: allow logstash traffic
  ufw: rule=allow to_port={{ item.0.port }} proto={{ item.0.protocol }} src={{ item.1|default('127.0.0.1') }}
  with_subelements:
    - "{{ logstash.firewall }}"
    - src
  tags:
    - firewall

- meta: flush_handlers

- name: enable and start logstash service
  service: name=logstash state=started enabled=yes

- include: checks.yml
  when: sensu.client.enable_checks|default('True')|bool
  tags: sensu-checks

- include: metrics.yml
  when: sensu.client.enable_metrics|default('True')|bool
  tags: sensu-metrics

- include: serverspec.yml
  when: serverspec.enabled|default("True")|bool
  tags: serverspec
