#!/bin/bash

ssh-keygen -b 2048 -t rsa -f test/deployer/key -q -N ""
mv test/deployer/key.pub test/target

docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL"
docker build -t target test/extension
docker start target

docker pull deployblue/deployer
docker run --name deployer -v $(pwd)/test/deployer/key:/app/key -v $(pwd)/roles:/app -v $(pwd)/test/ext.yml:/app/main.yml --link target deployblue/deployer

docker commit target deployblue/extension:$TARGET_VERSION
docker push deployblue/extension:$TARGET_VERSION
