#!/bin/bash

ssh-keygen -b 2048 -t rsa -f test/deployer/key -q -N ""
mv test/deployer/key.pub test/target

docker login -u="$DOCKER_USER" -p="$DOCKER_PASS" -e="$DOCKER_EMAIL"
docker build -t deployer test/deployer
docker build -t target test/target

docker create --name target target
docker start target

docker run --name deployer -v $(pwd)/roles:/app/roles -v $(pwd)/test/idempotency_test.yml:/app/main.yml --link target deployer
docker start -a deployer

docker cp deployer:/app/report .

count=1
oks=$(cat report | sed -n 's/target.*ok=\([0-9]*\).*/\1/p')
failed=$(cat report | sed -n 's/target.*failed=\([0-9]*\).*/\1/p')
changes=$(cat report | sed -n 's/target.*changed=\([0-9]*\).*/\1/p')
for change in $changes
do
   if [[ "$count" = 2 && "$change" -ne 0 ]]
   then
       cat report
       echo "Failed idempotency test.  Subsequent change count $change exceeds zero"
       exit 1
   fi
   count=$((($count + 1)))
done

count=1
for failure in $failed
do
   count=$((($count + 1)))
   if [ "$failure" -ne 0 ]
   then
       cat report
       echo "Playbook failure. Failure count $failure exceeds zero"
       exit 1
   fi
done

count=1
for ok in $oks
do
   count=$((($count + 1)))
   prevok=$ok
   if [[ "$count" -gt 1 &&  "$ok" -ne "$prevok" ]]
   then
       cat report
       echo "Failed idempotency test.  Previous 'ok' count $prev does not match current ok count $ok"
       exit 1
   else
       echo "Idempotency test successful."
       docker commit target deployblue/tcitest:$TARGET_VERSION
       docker push deployblue/tcitest:$TARGET_VERSION
   fi
done
