sudo: required

language: python

services:
  - docker

before_install:
- docker build -t deployer deployer
- docker build -t target target 

- docker create --name target target
- docker start target

- docker run --name deployer --link target deployer
- docker start -a deployer

- docker cp deployer:/app/report .
- docker logs deployer
- docker logs target 

script:
- cat report
