sudo: required

language: bash

services:
  - docker

before_install:
- docker build -t deployer test/deployer
- docker build -t target test/target 

- docker create --name target target
- docker start target

- docker run --name deployer -v $(pwd)/roles:/app/roles -v $(pwd)/main.yml:/app/main.yml --link target deployer
- docker start -a deployer

- docker cp deployer:/app/report . 

script:
- ./test/idempotency_results
