#!/bin/bash

count=1
ok=$(cat report | sed -n 's/.*ok=\([0-9]*\).*/\1/p')
failed=$(cat report | sed -n 's/.*failed=\([0-9]*\).*/\1/p')
changes=$(cat report | sed -n 's/.*changed=\([0-9]*\).*/\1/p')
for change in $changes
do
   echo change $count is $change
   count=$((($count + 1)))
done

count=1
for success in $ok
do
   echo ok $count is $success
   count=$((($count + 1)))
done

count=1
for failure in $failed
do
   echo failure $count is $failure
   count=$((($count + 1)))
done
