---
- name: add any dependent repository keys from url
  apt_key:
    url: "{{ item.key_url }}"
    validate_certs: "{{ item.validate_certs|default(omit) }}"
  with_items: "{{ repos }}"
  when: repos is defined and item.key_url is defined

# things like keyrings may come as packages vs. keys
- name: add any dependent repository key packages
  apt: pkg="{{ item.key_package }}"
  with_items: "{{ repos }}"
  when: repos is defined and item.key_package is defined

- name: add any dependent repositories
  apt_repository:
    repo: "{{ item.repo }}"
    update_cache: true
    validate_certs: "{{ item.validate_certs|default(omit) }}"
  with_items: "{{ repos }}"
  when: repos is defined
