---
- name: refresh cert auths
  command: update-ca-certificates

- name: restart logstash-forwarder
  service: name=logstash-forwarder state=restarted

- name: stop logstash-forwarder
  service: name=logstash-forwarder state=stopped
