---
# tasks file for mediapeers.filebeat

- name: Debian - Install chkconfig
  apt:
    name: chkconfig
    state: present
  when:
    - ansible_os_family == 'Debian'
    - ansible_distribution_release == 'wheezy'

- name: Check if apt-transport-https is installed
  shell: dpkg-query -W 'apt-transport-https'
  ignore_errors: 'true'
  register: is_apthttps

- name: Install apt-transport-https
  apt:
    name: apt-transport-https
    state: present
  when: is_apthttps | failed

- name: Creates directory
  file: path=/etc/pki/tls/certs state=directory

- name: Installing certificates
  copy: src=logstash-forwarder.crt dest=/etc/pki/tls/certs/logstash-forwarder.crt

- name: Installing key
  copy: src=logstash-forwarder.key dest=/etc/pki/tls/certs/logstash-forwarder.key


- name: Add elastic apt repo key (for all elastic software)
  apt_key:
    url: "https://artifacts.elastic.co/GPG-KEY-elasticsearch"
    state: present

# Install filebeat as a logstash client (to deliver logs), just for demoing

- name: Add filebeat apt repo
  apt_repository:
    repo: "deb https://artifacts.elastic.co/packages/5.x/apt stable main"
    update_cache: true
    state: present

- name: Install filebeat apt package
  apt:
    name: "filebeat={{ filebeat_version }}"
    state: present

- name: Creates filebeat conf directory
  file: path=/etc/filebeat/conf.d state=directory

- name: Configure filebeat to read from logfiles and deliver to logstash
  template:
    src: "{{ filebeat_conf_template }}.j2"
    dest: /etc/filebeat/filebeat.yml
  notify: restart filebeat

- name: Enable filebeat on bootup and ensure it's started
  service:
    name: filebeat
    enabled: true
